import { EmptyState, PageHeader, Panel } from "@/components/ops/OpsUi";
import { requireWorkbenchOwner } from "@/lib/auth/workbench-session";
import { copyableContent } from "@/lib/content/production";
import { getOpsStore } from "@/lib/ops/repository";
import { restoreContentVersion, saveContentDraft } from "../actions";

export default async function ContentDraftsPage({ searchParams }: { searchParams: Promise<{ taskId?: string; draftId?: string }> }) {
  await requireWorkbenchOwner(); const { taskId, draftId } = await searchParams; const store = await getOpsStore(); const drafts = await store.listContentDrafts(undefined, taskId); const draft = drafts.find((item) => item.id === draftId) || drafts[0];
  if (!draft) return <><PageHeader title="草稿编辑" /><EmptyState title="暂无草稿" description="先在内容生产中心生成一条内容。" /></>;
  const versions = await store.listContentVersions(draft.id); const copy = copyableContent(draft, "plain");
  return <><PageHeader title="草稿编辑" description="保存前会创建版本；复制内容不会附带字段标签。" /><div className="content-editor-grid"><Panel title="编辑草稿"><form className="ops-form-grid" action={saveContentDraft}><input name="id" type="hidden" value={draft.id} /><label className="ops-field wide"><span>标题</span><input name="title" defaultValue={draft.title} /></label><label className="ops-field wide"><span>摘要</span><textarea name="summary" defaultValue={draft.summary} /></label><label className="ops-field wide"><span>正文</span><textarea className="content-body-input" name="body" defaultValue={draft.body} /></label><label className="ops-field wide"><span>FAQ</span><textarea name="faq" defaultValue={draft.faq} /></label><label className="ops-field"><span>SEO 标题</span><input name="seoTitle" defaultValue={draft.seoTitle} /></label><label className="ops-field"><span>SEO 描述</span><input name="seoDescription" defaultValue={draft.seoDescription} /></label><label className="ops-field"><span>建议关键词</span><input name="suggestedKeywords" defaultValue={draft.suggestedKeywords} /></label><label className="ops-field"><span>状态</span><select name="status" defaultValue={draft.status}>{["草稿", "待审核", "已完成", "已交付", "已发布", "已作废"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="ops-field wide"><span>内部备注</span><textarea name="internalNotes" defaultValue={draft.internalNotes} /></label><label className="ops-field wide"><span>本次修改说明</span><input name="changeNote" /></label><button className="ops-button ops-button-primary">保存新版本</button></form></Panel><aside className="ops-stack"><Panel title="可复制正文"><textarea className="content-copy-preview" readOnly value={copy} /><p className="content-muted">纯净复制与公众号格式均不包含“标题：”等字段标签。</p></Panel><Panel title="版本记录">{versions.map((version) => <form action={restoreContentVersion} className="content-version-row" key={version.id}><input name="draftId" type="hidden" value={draft.id} /><input name="versionId" type="hidden" value={version.id} /><span>v{version.versionNumber} · {version.changeNote || "无说明"}</span><button className="ops-text-link">恢复</button></form>)}</Panel></aside></div></>;
}
