import type { StoreProfileForPrompt } from "./scenes";

export type StoreProfileSummaryPromptInput = {
  extractedText: string;
  storeProfile: StoreProfileForPrompt;
};

export function buildStoreProfileSummaryPrompt({ extractedText, storeProfile }: StoreProfileSummaryPromptInput): string {
  return [
    "请把下面的本地健康门店资料整理成一份店铺资料摘要。",
    "只输出一个合法 JSON 对象，不要输出 Markdown 代码块，不要在 JSON 前后添加解释。",
    'JSON 结构：{"summary":"店铺资料摘要正文"}',
    "摘要正文控制在 800-1500 字以内，保留真实、可用于后续生成文案的信息。",
    "如果资料中没有的信息，请写“资料中未明确”，不要编造。",
    "医疗健康合规要求：避免使用根治、治愈、保证有效、百分百、第一、最有效、永久、无副作用、包好、神医、祖传秘方、治疗疾病等夸大表达。",
    "优先使用调理、改善体验、缓解不适感、日常养护、辅助放松、适合了解、建议到店咨询、以实际体验为准等安全表达。",
    "摘要必须按以下中文结构输出到 summary 字段中：",
    "【店铺基础信息】",
    "* 店铺名称：",
    "* 门店类型：",
    "* 所在区域：",
    "* 服务人群：",
    "* 营业时间：",
    "* 联系方式：",
    "",
    "【核心项目】",
    "* 项目1：",
    "* 项目2：",
    "* 项目3：",
    "",
    "【项目卖点】",
    "* 卖点1：",
    "* 卖点2：",
    "* 卖点3：",
    "",
    "【适合宣传的内容】",
    "* 适合小红书宣传的角度：",
    "* 适合朋友圈宣传的角度：",
    "* 适合美团/点评宣传的角度：",
    "* 适合抖音/快手宣传的角度：",
    "",
    "【价格/套餐信息】",
    "* 如果资料中有价格，请提取。",
    "* 如果没有价格，请写“资料中未明确”。",
    "",
    "【服务流程】",
    "* 客户到店后的大致流程：",
    "",
    "【注意事项】",
    "* 哪些内容不能夸大：",
    "* 哪些表达需要合规：",
    "",
    "【可用于生成文案的店铺关键词】",
    "* 关键词1：",
    "* 关键词2：",
    "* 关键词3：",
    "",
    "账号内已有门店资料：",
    `店铺名称：${storeProfile.storeName}`,
    `门店类型：${storeProfile.storeType}`,
    `所在区域：${storeProfile.cityArea}`,
    `主营项目：${storeProfile.mainProjects || "未填写"}`,
    `门店优势：${storeProfile.storeAdvantages || "未填写"}`,
    "",
    "商户粘贴的店铺原始资料如下：",
    extractedText,
  ].join("\n");
}
