import Link from "next/link";
import { EmptyState, PageHeader, Panel, StatusBadge } from "@/components/ops/OpsUi";
import { requireWorkbenchOwner } from "@/lib/auth/workbench-session";
import { contentLabels } from "@/lib/content/production";
import { getOpsStore } from "@/lib/ops/repository";
import { opsContentTaskStatuses, opsContentTypes } from "@/lib/ops/types";
import { batchGenerateContentTasks, generateContentTask, saveContentKeyword, saveContentTask, saveStyleSample } from "./actions";

export default async function ContentCenterPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireWorkbenchOwner(); const query = await searchParams; const store = await getOpsStore();
  const [clients, organizations, tasks, styleSamples, keywords] = await Promise.all([store.listClients(), store.listOrganizations(), store.listContentTasks({ organizationId: query.organizationId, contentType: query.contentType, status: query.status, keyword: query.keyword }), query.organizationId ? store.listStyleSamples(query.organizationId) : Promise.resolve([]), query.organizationId ? store.listKeywords(query.organizationId) : Promise.resolve([])]);
  const clientById = new Map(clients.map((client) => [client.id, client])); const orgById = new Map(organizations.map((item) => [item.id, item]));
  const eligible = tasks.filter((task) => task.status === "待生成");
  return <>
    <PageHeader title="内容生产中心" description="仅使用机构当前真实资料生成；任务、草稿、版本与生成记录均可追溯。" />
    <Panel><form className="content-filter" action="/lvminglei/content"><select name="organizationId" defaultValue={query.organizationId || ""}><option value="">全部机构</option>{organizations.filter((item) => item.active).map((item) => <option value={item.id} key={item.id}>{item.organizationName}</option>)}</select><select name="contentType" defaultValue={query.contentType || ""}><option value="">全部内容类型</option>{opsContentTypes.map((type) => <option value={type} key={type}>{contentLabels[type]}</option>)}</select><select name="status" defaultValue={query.status || ""}><option value="">全部状态</option>{opsContentTaskStatuses.map((status) => <option key={status}>{status}</option>)}</select><input defaultValue={query.keyword || ""} name="keyword" placeholder="关键词" /><button className="ops-button ops-button-secondary">筛选</button></form></Panel>
    <section className="content-split"><Panel title="新建内容任务"><form action={saveContentTask} className="ops-form-grid"><label className="ops-field"><span>机构</span><select name="organizationId" required defaultValue={query.organizationId || ""}><option value="" disabled>选择机构</option>{organizations.filter((item) => item.active).map((item) => <option value={item.id} key={item.id}>{item.organizationName}</option>)}</select></label><label className="ops-field"><span>内容类型</span><select name="contentType">{opsContentTypes.map((type) => <option value={type} key={type}>{contentLabels[type]}</option>)}</select></label><label className="ops-field"><span>计划生成</span><input name="plannedGenerationDate" type="date" /></label><label className="ops-field"><span>计划发布</span><input name="plannedPublishDate" type="date" /></label><label className="ops-field wide"><span>选题</span><input name="topic" required placeholder="只填写基于真实机构资料的选题" /></label><label className="ops-field"><span>标题方向</span><input name="titleDirection" /></label><label className="ops-field"><span>主关键词</span><input name="primaryKeyword" /></label><label className="ops-field"><span>次关键词</span><input name="secondaryKeywords" /></label><label className="ops-field wide"><span>目标人群</span><input name="targetAudience" /></label><label className="ops-field wide"><span>内部备注</span><textarea name="notes" /></label><button className="ops-button ops-button-primary" type="submit">保存任务</button></form></Panel>
      <Panel title="批量生成"><p className="content-muted">本次仅处理列表中“待生成”任务。每条独立执行，部分失败不会回滚已成功内容。</p><form action={batchGenerateContentTasks}><input name="taskIds" type="hidden" value={eligible.map((task) => task.id).join(",")} /><input name="confirmed" type="hidden" value="yes" /><button className="ops-button ops-button-primary" disabled={!eligible.length} type="submit">确认批量生成（{eligible.length}）</button></form></Panel></section>
    {query.organizationId ? <section className="content-split"><Panel title="风格样本"><form action={saveStyleSample} className="ops-form-grid"><input name="organizationId" type="hidden" value={query.organizationId} /><label className="ops-field"><span>内容类型</span><select name="contentType">{opsContentTypes.map((type) => <option key={type} value={type}>{contentLabels[type]}</option>)}</select></label><label className="ops-field"><span>样本标题</span><input name="title" required /></label><label className="ops-field wide"><span>样本文案</span><textarea name="content" required /></label><button className="ops-button ops-button-secondary">添加样本</button></form>{styleSamples.length ? <div className="content-compact-list">{styleSamples.slice(0, 5).map((item) => <span key={item.id}>{item.title || "未命名样本"}</span>)}</div> : <p className="content-muted">尚未添加样本。</p>}</Panel><Panel title="关键词库"><form action={saveContentKeyword} className="ops-form-grid"><input name="organizationId" type="hidden" value={query.organizationId} /><label className="ops-field"><span>关键词</span><input name="keyword" required /></label><label className="ops-field"><span>类型</span><input name="keywordType" placeholder="核心词" /></label><label className="ops-field wide"><span>备注</span><input name="notes" /></label><button className="ops-button ops-button-secondary">添加关键词</button></form>{keywords.length ? <div className="content-compact-list">{keywords.filter((item) => item.active).map((item) => <span key={item.id}>{item.keyword}</span>)}</div> : <p className="content-muted">尚未添加关键词。</p>}</Panel></section> : null}
    <Panel title="内容任务列表">{tasks.length ? <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>选题</th><th>机构</th><th>类型 / 日期</th><th>状态</th><th>操作</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><strong>{task.topic || "未命名选题"}</strong><small>{task.primaryKeyword || "未设关键词"}</small></td><td>{clientById.get(task.clientId)?.clientName || "—"}<small>{orgById.get(task.organizationId)?.organizationName || "—"}</small></td><td>{contentLabels[task.contentType]}<small>{task.plannedGenerationDate || "未计划"}</small></td><td><StatusBadge status={task.status} /></td><td><form action={generateContentTask}><input name="taskId" type="hidden" value={task.id} /><button className="ops-text-link" disabled={task.status === "生成中" || task.status === "已作废"}>生成</button></form><Link className="ops-text-link" href={`/lvminglei/content/drafts?taskId=${task.id}`}>草稿</Link></td></tr>)}</tbody></table></div> : <EmptyState title="还没有内容任务" description="创建任务后，系统会在月历和此列表中显示真实计划。" />}</Panel>
  </>;
}
